name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install Brakeman
        run: gem install brakeman

      - name: Run Brakeman Security Audit
        run: brakeman -f json -o brakeman-report.json
        continue-on-error: true 

      - name: Upload Brakeman Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman-results
          path: brakeman-report.json
          retention-days: 14
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.4.1']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Setup database
      run: |
        RAILS_ENV=test bundle exec rails db:create
        RAILS_ENV=test bundle exec rails db:migrate

    - name: Run tests
      env:
        RAILSGOAT_MAINTAINER: true
      run: bundle exec rspec

    - name: Run security audit
      run: bundle exec bundle-audit check --update
      continue-on-error: true
